-- Copyright (C) 2026 JPSUN

CREATE TABLE llx_jpsun_fichinter_fr37 (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_fichinter integer NOT NULL,
  fk_user_creat integer,
  fk_user_modif integer,
  datec datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  present_on_site tinyint DEFAULT NULL,
  intervention_object varchar(64),
  intervention_object_other text,
  panel_qty integer DEFAULT NULL,
  roof_type varchar(64),
  roof_type_other text,
  install_type varchar(64),
  install_type_other text,
  roof_access_json text,
  electrical_connection varchar(64),
  risk_identified_json text,
  risk_other text,
  prevention_measures_json text,
  collective_protection_json text,
  individual_protection_json text,
  lift_planned tinyint DEFAULT NULL,
  ladder_planned tinyint DEFAULT NULL,
  lifeline_planned tinyint DEFAULT NULL,
  epi_checked tinyint DEFAULT NULL,
  safety_rules_json text,
  safety_instructions text,
  inverter_location text,
  panel_layout text,
  works_done text,
  consuel_case varchar(32),
  check_dc_connectors tinyint DEFAULT 0,
  check_ac_box tinyint DEFAULT 0,
  check_cables_trunking tinyint DEFAULT 0,
  check_grounds tinyint DEFAULT 0,
  check_labels tinyint DEFAULT 0,
  earth_value double(24,8) DEFAULT NULL,
  inverter_type varchar(255),
  inverter_serial varchar(255),
  inverter_power double(24,8) DEFAULT NULL,
  connection_type varchar(64),
  wifi_reason text,
  sim_info text
) ENGINE=innodb;

